#ifdef __cplusplus
extern "C" {
#endif
/*
// declare Ruby registration method generated by SWIG in rhoconnect-client_wrap.c
extern void Init_Rhoconnect-client(void);

// this method executed once on start of program
void Init_Rhoconnect-client_extension(void) {
	// execute initialization of Ruby registration (generated by SWIG)
	Init_Rhoconnect-client();

	// You can add some code to this place:


}
*/
#ifdef __cplusplus
} //extern "C"
#endif