
$rhodespath = File.expand_path '../../rhodes'
$rootpath = File.expand_path '..'
$sharedpath = File.join $rhodespath, 'platform', 'shared'

require File.join($rhodespath, "lib", "build", "jake.rb")

task :config

rhobuildyml = File.join $rhodespath, 'rhobuild.yml'
rhobuildyml = ENV["RHOBUILD"] unless ENV["RHOBUILD"].nil?

$rhoconfig = Jake.config(File.open(rhobuildyml))
$rhoconfig["platform"] = 'android'

$appconfig = Jake.config(File.open('build.yml'))

load File.join("Java", "Android", "build", "android.rake")


