#ifdef __cplusplus
extern "C" {
#endif

// declare Ruby registration method generated by SWIG in rhoconnect-client_wrap.c
extern void Init_SyncEngine(void);
extern void initRhoconnectClient();

// this method executed once on start of program
void Init_Rhoconnectclient_extension(void) {
	// execute initialization of Ruby registration (generated by SWIG)
	Init_SyncEngine();


	initRhoconnectClient();
}

#ifdef __cplusplus
} //extern "C"
#endif