def build_extension(name)
  require File.join($rootdir, 'lib/build/jake.rb')
  args = ['-o', 'Makefile', '-r', '-spec', 'macx-g++', "#{name}.pro", "QMAKE_MAC_SDK='#{$sdkroot}'", "RHODES_ROOT='#{$rootdir}'"]
  puts Jake.run($qmake,args)
  fail "[qmake #{name}.pro]" unless $? == 0
  puts Jake.run($make, ['clean'])
  fail "[make clean]" unless $? == 0
  puts Jake.run($make, ['all'])
  fail "[make all]" unless $? == 0
end

namespace "build" do
  task :config do
    $rootdir = ENV['RHO_ROOT']
    raise "RHO_ROOT is not set" if $rootdir.nil?
    $sdkroot = ENV['SDKROOT']
    raise "SDKROOT is not set" if $sdkroot.nil?
    $qmake = ENV['RHO_QMAKE']
    raise "RHO_QMAKE is not set" if $qmake.nil?
    $make = "make"
  end

  task :all => :config do
    build_extension('rhoconnect-client')
  end
end

task :default => "build:all"
